image: gitlab.libriciel.fr:4567/docker/android-builder:latest

stages:
  - submodules
  - test
  - build


# Jobs fetch_submodules

refresh_submodule_develop:
  stage: submodules
  except:
    - master
  script:
    - rm -rf ./mupdffragment
    - git clone -b develop https://gitlab.libriciel.fr/librairies/MupdfAndroid.git mupdffragment


refresh_submodule_master:
  stage: submodules
  only:
    - master
  script:
    - rm -rf ./mupdffragment
    - git clone -b master https://gitlab.libriciel.fr/librairies/MupdfAndroid.git mupdffragment


# Jobs test

local_unit_test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew test --continue


instrumented_unit_test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew connectedCheck --continue


# Jobs build

build_develop:
  stage: build
  except:
    - master
  script:
    - ./gradlew assembleDebug


build_release:
  stage: build
  only:
    - master
  script:
    - ./gradlew assembleDebug

