image: gitlab.libriciel.fr:4567/docker/android-builder:latest

before_script:
    - eval $(ssh-agent -s)
    # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
    - ssh-add <(echo "$SECRET_VARIABLES_ID_RSA")
    # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
    # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
    - mkdir -p ~/.ssh 
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config 
    - git clone -b develop https://scm.adullact.net/anonscm/git/mupdfandroid/mupdfandroid.git mupdffragment || echo "Submodule already fetched"

stages:
    - submodules
    - test
    - build


# Jobs fetch_submodules

refresh_submodule_develop:
  stage: submodules
  except:
    - master
  script:
    - rm -rf ./mupdffragment
    - git clone -b develop https://gitlab.libriciel.fr/librairies/MupdfAndroid.git mupdffragment


refresh_submodule_master:
  stage: submodules
  only:
    - master
  script:
    - rm -rf ./mupdffragment
    - git clone -b master https://gitlab.libriciel.fr/librairies/MupdfAndroid.git mupdffragment


# Jobs test

local_unit_test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew test --continue


instrumented_unit_test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew connectedCheck --continue


# Jobs build

build_develop:
  stage: build
  except:
    - master
  script:
    - ./gradlew assembleDebug


build_release:
  stage: build
  only:
    - master
  script:
    - ./gradlew assembleDebug

