image: gitlab.libriciel.fr:4567/docker/android-builder:latest

before_script:
  # Force submodule refresh
  - [[ $CI_BUILD_REF_NAME = "master" ]] && BUILD_TYPE="master" || BUILD_TYPE="develop"
  - rm -rf ./mudpffragment/*
  - git clone -b BUILD_TYPE https://scm.adullact.net/anonscm/git/mupdfandroid/mupdfandroid.git mupdffragment

build_apk:
  script:
    - [[ BUILD_TYPE = "master" ]] ./gradlew assembleRelease || ./gradlew assembleDebug
