image: gitlab.libriciel.fr:4567/docker/android-builder:latest

before_script:
  - rm -rf ./mupdffragment

stages:
  - submodules
  - test
  - build


# Jobs fetch_submodules

refresh_submodule_develop:
  stage: submodules
  except:
    - master
  script:
    - git clone -b develop https://scm.adullact.net/anonscm/git/mupdfandroid/mupdfandroid.git mupdffragment


refresh_submodule_master:
  stage: submodules
  only:
    - master
  script:
    - git clone -b master https://scm.adullact.net/anonscm/git/mupdfandroid/mupdfandroid.git mupdffragment


# Jobs test

local_unit_test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew test --continue


instrumented_unit_test:
  stage: test
  allow_failure: true
  script:
    - ./gradlew connectedCheck --continue


# Jobs build

build_develop:
  stage: build
  except:
    - master
  script:
    - ./gradlew assembleDebug


build_release:
  stage: build
  only:
    - master
  script:
    - ./gradlew assembleDebug

