image: gitlab.libriciel.fr:4567/docker/android-builder:latest

before_script:
  - git submodule update --recursive

build_apk_debug:
  script:
    - ./gradlew assembleDebug

build apk_release:
  script:
    - ./gradlew assembleRelease