image: gitlab.libriciel.fr:4567/docker/android-builder:latest

before_script:
  - echo $CI_BUILD_REF_NAME

build_apk_develop:
  script:
    - git clone -b develop https://scm.adullact.net/anonscm/git/mupdfandroid/mupdfandroid.git mupdffragment
    - ./gradlew assembleDebug

build apk_release:
  script:
    - git clone -b master https://scm.adullact.net/anonscm/git/mupdfandroid/mupdfandroid.git mupdffragment
    - ./gradlew assembleRelease